export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const SET_CURRENT = 'SET_CURRENT'
export const CLEAR_CURRENT = 'CLEAR_CURRENT'
export const ITEM_ERROR = 'ITEM_ERROR'
export const FILTER_ITEMS = 'FILTER_ITEMS'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const HIDE_ITEMS = 'HIDE_ITEMS'
// alerts may also be useful to alert players to events ingame such as out of bounds etc
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const PLAYER_LOADED = 'PLAYER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// stats
export const GET_STATS = 'GET_STATS'
export const BOOST_HEALTH = 'BOOST_HEALTH'
export const DECREASE_HEALTH = 'DECREASE_HEALTH'
export const INCREASE_POINTS = 'INCREASE_POINTS'
export const ADD_XP = 'ADD_XP'
export const UPDATE_HISTORY = 'UPDATE_HISTORY'
export const ERROR = 'ERROR'
